### ISSUE TITLE
Platforms Page: создать страницу списка платформ

### ISSUE THREAD

**Issue by HushchaNatallia** [Power-Rangers-3/Front-end#71]
1. Создать публичную страницу для поиска платформ
2. Верстка страницы
3. Добавить ссылку на нее в header
4. Для авторизованных пользователей: кнопка на каждой платформе для добавление ее в избранное

**Comment by pyropetrick** [comment]
Ожидаем:
1. Макет
2. Эндпоинты бэкенда
